/**
 * generated by Xtext
 */
package eu.scape_project.pw.generator;

import com.google.common.collect.Iterables;
import eu.scape_project.pw.simulator.Event;
import eu.scape_project.pw.simulator.Simulation;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

@SuppressWarnings("all")
public class SimulatorGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Simulation> _filter = Iterables.<Simulation>filter(_iterable, Simulation.class);
    for (final Simulation e : _filter) {
      String _name = e.getName();
      String _plus = ("/simulator/" + _name);
      String _plus_1 = (_plus + ".java");
      CharSequence _compile = this.compile(e);
      fsa.generateFile(_plus_1, _compile);
    }
    TreeIterator<EObject> _allContents_1 = resource.getAllContents();
    Iterable<EObject> _iterable_1 = IteratorExtensions.<EObject>toIterable(_allContents_1);
    Iterable<Event> _filter_1 = Iterables.<Event>filter(_iterable_1, Event.class);
    for (final Event e_1 : _filter_1) {
      String _name_1 = e_1.getName();
      String _plus_2 = ("/simulator/" + _name_1);
      String _plus_3 = (_plus_2 + ".java");
      CharSequence _compileEvent = this.compileEvent(e_1);
      fsa.generateFile(_plus_3, _compileEvent);
    }
  }
  
  public CharSequence compile(final Simulation s) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("package simulator;");
    _builder.newLine();
    _builder.append("import eu.scape_project.App;");
    _builder.newLine();
    _builder.append("public class ");
    String _name = s.getName();
    _builder.append(_name, "");
    _builder.append(" { ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("App test = new App(); ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("test.test(); \t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence compileEvent(final Event e) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("package simulator;");
    _builder.newLine();
    _builder.append("import eu.scape_project.*;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("public class ");
    String _name = e.getName();
    _builder.append(_name, "");
    _builder.append(" extends Event{ ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t \t");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected void executeEvent() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(\"Hello  ");
    String _name_1 = e.getName();
    _builder.append(_name_1, "		");
    _builder.append(" \"); ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
