/*
 * generated by Xtext
 */
package eu.scape_project;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimulatorRuntimeModule extends eu.scape_project.AbstractSimulatorRuntimeModule {

}
