/*
 * generated by Xtext
 */
package eu.scape_project.pw.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.scape_project.pw.ui.internal.SimulatorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimulatorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimulatorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimulatorActivator.getInstance().getInjector(SimulatorActivator.EU_SCAPE_PROJECT_PW_SIMULATOR);
	}
	
}
