/*
* generated by Xtext
*/
package eu.scape_project.pw.ui.contentassist;

import eu.scape_project.pw.ui.contentassist.AbstractSimulatorProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimulatorProposalProvider extends AbstractSimulatorProposalProvider {

}
