/*
 * generated by Xtext
 */
package eu.scape_project.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimulatorUiModule extends eu.scape_project.ui.AbstractSimulatorUiModule {
	public SimulatorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
