/*
* generated by Xtext
*/
package eu.scape_project.pw.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SimulatorOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
