/*
* generated by Xtext
*/
package eu.scape_project.pw.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import eu.scape_project.pw.services.SimulatorGrammarAccess;

public class SimulatorParser extends AbstractContentAssistParser {
	
	@Inject
	private SimulatorGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected eu.scape_project.pw.ui.contentassist.antlr.internal.InternalSimulatorParser createParser() {
		eu.scape_project.pw.ui.contentassist.antlr.internal.InternalSimulatorParser result = new eu.scape_project.pw.ui.contentassist.antlr.internal.InternalSimulatorParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSimulationAccess().getGroup(), "rule__Simulation__Group__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getEventAccess().getGroup_3(), "rule__Event__Group_3__0");
					put(grammarAccess.getSimulationAccess().getNameAssignment_1(), "rule__Simulation__NameAssignment_1");
					put(grammarAccess.getSimulationAccess().getEventsAssignment_3(), "rule__Simulation__EventsAssignment_3");
					put(grammarAccess.getEventAccess().getNameAssignment_1(), "rule__Event__NameAssignment_1");
					put(grammarAccess.getEventAccess().getEventsAssignment_3_1(), "rule__Event__EventsAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			eu.scape_project.pw.ui.contentassist.antlr.internal.InternalSimulatorParser typedParser = (eu.scape_project.pw.ui.contentassist.antlr.internal.InternalSimulatorParser) parser;
			typedParser.entryRuleSimulation();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SimulatorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimulatorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
