/*
* generated by Xtext
*/
package eu.scape_project.pw.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractSimulatorJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(eu.scape_project.pw.simulator.SimulatorPackage.eINSTANCE);
		return result;
	}

}
