/*
* generated by Xtext
*/
package eu.scape_project.pw.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.scape_project.pw.services.SimulatorGrammarAccess;

public class SimulatorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimulatorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.scape_project.pw.parser.antlr.internal.InternalSimulatorParser createParser(XtextTokenStream stream) {
		return new eu.scape_project.pw.parser.antlr.internal.InternalSimulatorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Simulation";
	}
	
	public SimulatorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimulatorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
